/// Flutter icons Icones_Novos
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icones_Novos
///      fonts:
///       - asset: fonts/Icones_Novos.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Icones_Novos {
  Icones_Novos._();

  static const _kFontFam = 'Icones_Novos';
  static const String _kFontPkg = null;

  static const IconData cookie =
      IconData(0xf563, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cookie_bite =
      IconData(0xf564, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData candy_cane =
      IconData(0xf786, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
